### ISSUE TITLE
Fix get method (must get by playerNo)

### ISSUE THREAD

**Issue by Bimde** [Bimde/Blackjack-Server#17]
Change the ArrayList to ClientList

**Comment by xuwilliam01** [comment]
Clientlist had nullpoint issues so I had to change it to arraylist. We can keep it as an arraylist and get by the client (create new client with the playerNo we want and search, since I made compareTo by playerNo)

**Comment by Bimde** [comment]
Ok, I see then, I won't change it

**Comment by Bimde** [comment]
Changed to ClientList and fixed (due to having to create a new Client object each time in order to use get with ArrayList)
