### ISSUE TITLE
Server card broadcast

### ISSUE THREAD

**Issue by ecnivo** [Bimde/Blackjack-Server#2]
Server should broadcast the dealer's first card before dealing any cards to any players, because some decisions can be based off of the current card the dealer has.

However, the other cards (face down card, and others that are drawn until dealer reaches 17) can be broadcasted later, because those are not important.

**Comment by Bimde** [comment]
We already do this.

**Comment by Bimde** [comment]
Quick amendment: the order of which you receive your cards / the dealers face down / up card shouldn't matter realistically because you won't make any decisions (i.e. hit / stand) until you receive all of these cards anyway.

**Comment by ecnivo** [comment]
That is not the case. If you look under the documentation, the dealer's card is revealed at 8h, but the client is asked to express their action at 8f. F < H

**Comment by pcjl** [comment]
The steps under 8 are not in chronological order.

**Comment by Bimde** [comment]
Ok this makes sense Vince, this will be put in chronological order by tommorow
