### ISSUE TITLE
Multiple ai's crash randomly on certain occasions

### ISSUE THREAD

**Issue by Bimde** [Bimde/Blackjack-Server#22]
This only applies to AI's for some reason: maybe something to due with timing to messages and/ or specific AI case only.

**Comment by xuwilliam01** [comment]
Their responses must be too instant, or there is an inconsistency with the
communications

**Comment by Bimde** [comment]
If the reason is the former, we need to make changes, otherwise, we should be good (because the server isn't crashing or anything, it's them that's crashing)

**Comment by xuwilliam01** [comment]
Wait, its them thats crashing? Then its 95 percent chance its not our
fault. How many ai did you test this with?

**Comment by Bimde** [comment]
This isn't a server error. The error is caused by AI's not dealing with player disconnection + not dealing with potential variables in output (as specified in the doc).
