### ISSUE TITLE
Keep history of messages for new spectator?

### ISSUE THREAD

**Issue by Bimde** [Bimde/Blackjack-Server#23]

**Comment by pcjl** [comment]
What kind of messages? I know that spectators require some information in order to display their GUI properly (if they are a human spectator), but didn't we add the necessary information already?

**Comment by xuwilliam01** [comment]
Only for the current round, or we can tell them to wait till the next round

**Comment by Bimde** [comment]
This is not being implemented because new players / spectators will not be able to join a round once it's started.
