### ISSUE TITLE
Shuffle protocol

### ISSUE THREAD

**Issue by ecnivo** [Bimde/Blackjack-Server#25]
Can the shuffle protocol be changed, so that it's not whether or not the line exists, but something like:
"% SHUFFLE" and "% NOSHUFFLE"? 

It's easier for doing checks and not as much of a headache.

**Comment by Bimde** [comment]
It's not that difficult to add an if statement to optionally check for it. And unfortunately even if it is difficult, the specs cannot be changed once again because there are too many people trying to fix their code with the current specs + have already worked around this rule

**Comment by Bimde** [comment]
If this becomes a huge issue for everyone, we may consider it
