### ISSUE TITLE
Server broadcast timing

### ISSUE THREAD

**Issue by ecnivo** [Bimde/Blackjack-Server#3]
Are all broadcasts separated by 500ms?

**Comment by xuwilliam01** [comment]
No just the dealing of cards

**Comment by Bimde** [comment]
We could potentially make the mesaages separated by 500 ms (timer running to broadcast new messages every 500 ms). However, waiting for client input will definitely delay the next communication to everyone else. This means the delay is not = 500ms, but rather >= 500ms
