### ISSUE TITLE
Betting and client's coins

### ISSUE THREAD

**Issue by ecnivo** [Bimde/Blackjack-Server#32]
If a client's number of coins drops below 10, just kick them off as if they've lost. They can't bet anything anyway in the next round.

**Comment by pcjl** [comment]
This should already happen.

**Comment by Bimde** [comment]
This already happens

**Comment by ecnivo** [comment]
Well. Um. Not exactly. But sure!

I'm getting FORMATERROR, and my coins is at 7. So.

**Comment by Bimde** [comment]
Fixed by @pcjl .
