### ISSUE TITLE
Keeping track of each running game off the central server

### ISSUE THREAD

**Issue by xuwilliam01** [Bimde/Blackjack-Server#36]
We need to either somehow organize the console messages or create a gui that displays all the events from every game

**Comment by Bimde** [comment]
There shouldn't be any additional messages in the final build. This is only for debugging use. Creating a JTextArea in a JScrollPane which displays all input/outptut for each individual server seems to be a decent enough solution.

**Comment by Bimde** [comment]
We could potentially have a 'DEBUG' constant which caused the server to create this JFrame and display messages in it if it is true.

**Comment by Bimde** [comment]
All debugging messages are displayed in the JFrame. This can be turned on and off using the constant 'DEBUG'. No more changes to the GUI will be done.
