### ISSUE TITLE
Hit/doubledown protocol?

### ISSUE THREAD

**Issue by ecnivo** [Bimde/Blackjack-Server#5]
When it's a client's turn, the client says "hit" or "double down", are they replied by the server by a "<b># 0 rank suit</b>" message by the server?

**Comment by Bimde** [comment]
Yes

**Comment by ecnivo** [comment]
Is this sent to all clients or just the client whose turn it is? I think it should be sent to all clients, for card counting purposes. :wink:

**Comment by pcjl** [comment]
It is sent to all clients.
