### ISSUE TITLE
Shuffle

### ISSUE THREAD

**Issue by ecnivo** [Bimde/Blackjack-Server#7]
Is shuffle going to be at the end of each round (if it's going to be done in that instance?)

**Comment by Bimde** [comment]
The shuffle will be done every n rounds, n still undecided. However, there is no guarantee for n to remain consistent. This means you will only know that we are adding the old cards back into the deck and shuffling when 'SHUFFLE' is broadcasted

**Comment by Bimde** [comment]
Shuffling now set to: n% chance after each round + guaranteed shuffle if their aren't a minimum of  m cards per player in the deck.

**Comment by Bimde** [comment]
Values are still undecided, but currently:
n = 20%
m = 21
